In [1]:
import numpy as np

In [5]:
aa = np.random.randint(1, 100, 20)
print(aa)

[77 72 89 63 65 57 56 45 35 46 72 70 64 32 26 21 81  1 99 53]


In [7]:
aasortasc = np.sort(aa)
print(aasort)

[ 1 21 26 32 35 45 46 53 56 57 63 64 65 70 72 72 77 81 89 99]


In [8]:
aasortdesc = np.sort(aa)[::-1]
print(aasortdesc)

[99 89 81 77 72 72 70 65 64 63 57 56 53 46 45 35 32 26 21  1]


In [9]:
np1 = aasortdesc
np1

array([99, 89, 81, 77, 72, 72, 70, 65, 64, 63, 57, 56, 53, 46, 45, 35, 32,
       26, 21,  1])

In [10]:
np1[0] = 20

In [11]:
np1

array([20, 89, 81, 77, 72, 72, 70, 65, 64, 63, 57, 56, 53, 46, 45, 35, 32,
       26, 21,  1])

In [12]:
aasortdesc

array([20, 89, 81, 77, 72, 72, 70, 65, 64, 63, 57, 56, 53, 46, 45, 35, 32,
       26, 21,  1])

In [13]:
np1 = aasortdesc.copy()

In [14]:
print(np1)
print(aasortdesc)

[20 89 81 77 72 72 70 65 64 63 57 56 53 46 45 35 32 26 21  1]
[20 89 81 77 72 72 70 65 64 63 57 56 53 46 45 35 32 26 21  1]


In [15]:
np1[0] = 99

In [16]:
print(np1)
print(aasortdesc)

[99 89 81 77 72 72 70 65 64 63 57 56 53 46 45 35 32 26 21  1]
[20 89 81 77 72 72 70 65 64 63 57 56 53 46 45 35 32 26 21  1]


In [17]:
np1

array([99, 89, 81, 77, 72, 72, 70, 65, 64, 63, 57, 56, 53, 46, 45, 35, 32,
       26, 21,  1])

In [18]:
print(np.size(np1))

20


In [19]:
np2 = np.eye(4)

In [20]:
np2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np3 = np.full((3,4), 5)
print(np3)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
np3 = np.full((3,4), 6)
print(np3)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [23]:
np3

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [24]:
np3.T

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])