In [13]:
import numpy as np

In [14]:
aa = np.array([1, 2, 3, 4, 5])

In [15]:
aa = np.arange(1, 21)

In [16]:
aa.shape = (5,4)

In [17]:
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
aa.transpose()

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [19]:
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [21]:
np.append(aa, [21, 22, 23, 24])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [23]:
aa = np.append(aa, [21, 22, 23, 24])
print(aa)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [37]:
aa.shape = (7,4)

In [38]:
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [39]:
aa * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48],
       [50, 52, 54, 56]])

In [40]:
lst1 = [[1,2,3], [4,5,6], [7,8,9]] * 2

In [41]:
lst1

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [42]:
aa + 20

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [43]:
aa / 2

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5,  6. ],
       [ 6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. ]])

In [46]:
aa = np.arange(1, 21)
bb = np.arange(21, 41)
aa.shape = (4,5)
bb.shape = (4,5)
cc = aa + bb
print(aa, "\n")
print(bb, "\n")
print(cc)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]] 

[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]


In [48]:
aa = np.arange(1, 10)
bb = np.arange(11, 20)
aa.shape = (3, 3)
bb.shape = (3, 3)
cc = aa * bb
print(aa, "\n")
print(bb, "\n")
print(cc)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[11 12 13]
 [14 15 16]
 [17 18 19]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [51]:
aa = np.arange(1, 13)
bb = np.arange(11, 23)
aa.shape = (3, 4)
bb.shape = (3, 4)
cc = aa * bb
print(aa, "\n")
print(bb, "\n")
print(cc)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]] 

[[ 11  24  39  56]
 [ 75  96 119 144]
 [171 200 231 264]]


In [52]:
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
aa.sum()

78

In [54]:
aa.sum(axis=0)

array([15, 18, 21, 24])

In [55]:
aa.sum(axis=1)

array([10, 26, 42])

In [56]:
print(aa)
print(bb)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [57]:
aa - bb

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [58]:
np.subtract(aa, bb)

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [59]:
np.multiply(aa, bb)

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171, 200, 231, 264]])

In [60]:
print(aa)
print(bb)
print(np.mod(aa, bb))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
print(np.mod(bb, aa))

[[ 0  0  1  2]
 [ 0  4  3  2]
 [ 1  0 10 10]]


In [62]:
aa = np.array([1, 2, 3])
bb = np.array([4, 5, 6])
print(np.remainder(aa, bb))

[1 2 3]


In [63]:
print(np.remainder(bb, aa))

[0 1 0]


In [65]:
aa = np.arange(1, 10)
aa

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
aa

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
aa.mean()

5.0

In [70]:
aa.min()

1

In [71]:
aa.max()

9

In [72]:
aa.sort()

In [73]:
aa

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
aa = np.array([21, 22, 1, 3, 4])
aa.sort()

In [75]:
aa

array([ 1,  3,  4, 21, 22])

In [76]:
aa

array([ 1,  3,  4, 21, 22])

In [77]:
np.average(aa)

10.2