In [2]:
import numpy as np

In [3]:
aa = np.array([1, 2, 3, 4, 5])

In [5]:
print(type(aa))

<class 'numpy.ndarray'>


In [6]:
aa

array([1, 2, 3, 4, 5])

In [7]:
aa[0]

1

In [8]:
aa[2]

3

In [9]:
lst1 = [1, 2, 3, 4, 5]
aa = np.array(lst1)
print(aa)

[1 2 3 4 5]


In [10]:
lst2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
aa2 = np.array(lst2)
print(aa2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
aa2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(aa2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
aa2.dtype

dtype('int32')

In [14]:
aa2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=np.complex)
print(aa2)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j  8.+0.j]
 [ 9.+0.j 10.+0.j 11.+0.j 12.+0.j]]


In [15]:
# Complex Number
num = 1 + 2x    # Throws an error

SyntaxError: invalid syntax (<ipython-input-15-4583c4c6cb0b>, line 2)

In [16]:
# Complex Number
num = 1 + 2j

In [17]:
type(num)

complex

In [18]:
num.real

1.0

In [19]:
num.imag

2.0

In [20]:
print(aa2)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j  8.+0.j]
 [ 9.+0.j 10.+0.j 11.+0.j 12.+0.j]]


In [21]:
type(aa2)

numpy.ndarray

In [22]:
aa2.dtype

dtype('complex128')

In [23]:
aa2[0][0]

(1+0j)

In [24]:
aa2[0][0].real

1.0

In [25]:
aa2[0][0].imag

0.0

In [27]:
aa2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype=np.int64)
print(aa2.dtype)

int64


In [29]:
aa

array([1, 2, 3, 4, 5])

In [30]:
aa2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

In [31]:
aa.shape

(5,)

In [32]:
aa2.shape

(3, 4)

In [33]:
aa2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

In [34]:
aa2.shape

(3, 4)

In [35]:
aa2.shape = (4,3)

In [36]:
aa2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64)

In [38]:
aa2.shape

(4, 3)

In [39]:
aa2.shape = (2, 6)

In [40]:
aa2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]], dtype=int64)

In [41]:
aa2.shape

(2, 6)

In [42]:
aa2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

In [43]:
aa2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]], dtype=int64)

In [44]:
aa2 = aa2.reshape(3,4)

In [45]:
aa2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

### arange

In [46]:
aa = np.arange(10)
print(aa)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
aa = np.arange(10, 30)
print(aa)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [49]:
aa = np.arange(0, 20, 2)
print(aa)

[ 0  2  4  6  8 10 12 14 16 18]


In [50]:
aa = np.arange(12)
aa.shape = (3,4)
print(aa)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
aa = np.arange(1,13)
aa.shape = (3,4)
print(aa)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
aa = np.arange(24)
aa.shape = (2, 4, 3)
print(aa)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [53]:
aa.shape = (2,12)
print(aa)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [54]:
aa.dtype

dtype('int32')

In [55]:
aa.itemsize

4

In [60]:
aa.dtype = np.int64

In [61]:
aa.itemsize

8

### empty

In [62]:
aa = np.empty((3,2))

In [63]:
aa

array([[4.24399158e-314, 8.48798317e-314],
       [1.27319747e-313, 1.69759663e-313],
       [2.12199579e-313, 2.54639495e-313]])

In [64]:
aa = np.zeros((3,2))
print(aa)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [66]:
aa = np.ones((3,2))
print(aa)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [67]:
aa = np.linspace(1, 50, 50)
print(aa)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [68]:
aa = np.linspace(1, 25, 50)
print(aa)

[ 1.          1.48979592  1.97959184  2.46938776  2.95918367  3.44897959
  3.93877551  4.42857143  4.91836735  5.40816327  5.89795918  6.3877551
  6.87755102  7.36734694  7.85714286  8.34693878  8.83673469  9.32653061
  9.81632653 10.30612245 10.79591837 11.28571429 11.7755102  12.26530612
 12.75510204 13.24489796 13.73469388 14.2244898  14.71428571 15.20408163
 15.69387755 16.18367347 16.67346939 17.16326531 17.65306122 18.14285714
 18.63265306 19.12244898 19.6122449  20.10204082 20.59183673 21.08163265
 21.57142857 22.06122449 22.55102041 23.04081633 23.53061224 24.02040816
 24.51020408 25.        ]


In [73]:
aa = np.linspace(0, 20)
aa.shape=(10,5)
print(aa)

[[ 0.          0.40816327  0.81632653  1.2244898   1.63265306]
 [ 2.04081633  2.44897959  2.85714286  3.26530612  3.67346939]
 [ 4.08163265  4.48979592  4.89795918  5.30612245  5.71428571]
 [ 6.12244898  6.53061224  6.93877551  7.34693878  7.75510204]
 [ 8.16326531  8.57142857  8.97959184  9.3877551   9.79591837]
 [10.20408163 10.6122449  11.02040816 11.42857143 11.83673469]
 [12.24489796 12.65306122 13.06122449 13.46938776 13.87755102]
 [14.28571429 14.69387755 15.10204082 15.51020408 15.91836735]
 [16.32653061 16.73469388 17.14285714 17.55102041 17.95918367]
 [18.36734694 18.7755102  19.18367347 19.59183673 20.        ]]


In [74]:
aa = np.logspace(0, 10, 10)
print(aa)

[1.00000000e+00 1.29154967e+01 1.66810054e+02 2.15443469e+03
 2.78255940e+04 3.59381366e+05 4.64158883e+06 5.99484250e+07
 7.74263683e+08 1.00000000e+10]


In [75]:
aa = np.arange(20)
aa.shape = (4,5)
print(aa)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [76]:
aa[0]

array([0, 1, 2, 3, 4])

In [80]:
aa[0:1]

array([[0, 1, 2, 3, 4]])

In [82]:
aa[2:3]

array([[10, 11, 12, 13, 14]])

In [83]:
aa[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [84]:
aa[2:4, 2:5]

array([[12, 13, 14],
       [17, 18, 19]])

In [85]:
aa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])